- README.md
- examples/capybara/Gemfile.lock
- examples/rspec-capybara/Gemfile.lock
- examples/selenium/Gemfile.lock
- examples/watir/Gemfile.lock
- package.json
- Creating RSpec documentation in README.md
- Adding MiniTest example project
also:
- Upgrading gems in example projects
- setting private to true in package.json to prevent accidental publishing to npm
> Rspec docs

- README.md
- docs/Cucumber.md
- docs/RSpec.md
Splitting documentation from Readme into RSpec and Cucumber md's. 
Adding content from axe-core repo to Readme.
> Docs Reorganization

- docs/Cucumber.md
Thanks @ RamyaAnguraj for finding this problem with issue #19.
Closes #19
> Fixes typo in cucumber config docs

- package.json
- spec/lib/axe/configuration_spec.rb
- spec/lib/axe/core_spec.rb
Let's see if this makes the tests pass on Circle.
> chore: update axe-core to 2.3.1

- axe-matchers.gemspec
- lib/axe/matchers/be_accessible.rb
- spec/lib/axe/matchers/be_accessible_spec.rb
Updating Github so we can archive bitbucket/axe-matchers.
> Merge Bitbucket changes into Github

- examples/capybara/features/support/env.rb
- features/iframes.feature
- lib/axe/cucumber/step.rb
This fixes an issue which doesn't look like it ever worked... :(
> fix: Prevent Cucumber from choking on comments

- CHANGELOG.md
- axe-matchers.gemspec
- lib/axe/api/results.rb
- lib/axe/api/results/check.rb
- lib/axe/api/results/checked_node.rb
- lib/axe/api/results/rule.rb
- package-lock.json
- package.json
Merging Develop to Master for release of 2.1.1, contains below PR's
[x] - https://github.com/dequelabs/axe-matchers/pull/37
[x] - https://github.com/dequelabs/axe-matchers/pull/38
> feat: -> master - release 2.1.1

- CHANGELOG.md
- package.json
Merge back changes from release v2.2.1 to develop branch.
Closes issue: NA
> Chore: Release/v2.2.1 to Develop

- examples/rspec-capybara/Gemfile
- examples/rspec-capybara/Gemfile.lock
Updated gem deps to fix security warning.
Closes issue: NA
> fix: security vulnerability

- CHANGELOG.md
- axe-matchers.gemspec
- package-lock.json
- package.json
Merge this after https://github.com/dequelabs/axe-matchers/pull/54
> chore: update from master

- CHANGELOG.md
- package-lock.json
- package.json
- add `standard-version`
- rebuild `changelog` using `standard-version`
Closes issue:
> chore: add standard version for changelog

- package.json
- Update `axe-core` to `v3.3.0`
Closes issue:
- NA
> feat: update axe-core to v3.3.0

- .circleci/config.yml
- update version of Firefox and Geckodriver
Closes issue: NA
> chore (CI): update version of Firefox and Geckodriver

- package-lock.json
- package.json
Update axe-core to v3.3.1
Closes issue: NA
> feat: update axe-core to v3.3.1

- .circleci/config.yml
- CHANGELOG.md
- axe-matchers.gemspec
- package-lock.json
- package.json
Release `axe-matcher v2.4.1`
Review 10% (50 max) of the following (Product manager only):
---
Notes:
- Updated to `axe-core v3.3.1`
---
> chore: Release v2.4.1

- package-lock.json
- package.json
See title
Closes issue: https://github.com/dequelabs/attest-ruby/issues/87
> feat: update axe-core to v3.4.0

- CHANGELOG.md
- axe-matchers.gemspec
- package-lock.json
- package.json
See title
Closes issue: https://github.com/dequelabs/attest-ruby/issues/87
> chore: Release v2.5.0

- package-lock.json
- package.json
Closes issue: https://github.com/dequelabs/attest-ruby/issues/120
> feat: update axe-core to v3.5.0

- package-lock.json
- package.json
> feat: update axe-core to v3.5.1

- CHANGELOG.md
- axe-matchers.gemspec
- package-lock.json
- package.json
> chore: release v2.6.0

- package-lock.json
- package.json
> feat: update axe-core to v3.5.2

- axe-matchers.gemspec
- package-lock.json
- package.json
> chore: release v2.6.1

- .github/workflows/sync-master-develop.yml 
> ci: Add "sync branches" workflow

- .circleci/config.yml
- .circleci/publish.sh
- Rakefile
- packages/axe-core-api/Rakefile
- packages/axe-core-capybara/Rakefile
- packages/axe-core-cucumber/Rakefile
- packages/axe-core-rspec/Rakefile
- packages/axe-core-selenium/Rakefile
- packages/axe-core-watir/Rakefile
> ci: setup canary & production releases

- package-lock.json
- package.json
- version.rb
> chore: update version to 4.0.0

- .circleci/config.yml
Add GitHub release script to CI
Closes issue: 
- NA
> ci: add github release script

- .circleci/config.yml
- .circleci/install-geckodriver.sh
> ci: swap out install geckodriver script

- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
> chore: use axe-core `v4.0.2`

- README.md
> docs(README): fix typos in the README docs 

- README.md
> docs: add slack badge

- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
> chore: update to axe-core `v4.1.0`

- .circleci/config.yml
> ci: update ruby docker image

- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
> feat: bump axe-core to v4.1.2

- .github/review.yml
> chore: add security review

- .github/workflows/auto-assign-issues.yml
> ci: add github action to auto assign issues

- packages/axe-core-api/lib/loader.rb
- packages/axe-core-api/package.json
> feat: bump axe-core to 4.2.0

- package.json
- packages/axe-core-api/package.json
> feat: update axe-core to 4.2.1

- .github/PULL_REQUEST_TEMPLATE.md
> docs: remove security check from PR template

- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
- packages/axe-core-cucumber/e2e/capybara/features/a11y.feature
- packages/axe-core-cucumber/e2e/watir/features/a11y.feature
- packages/axe-core-rspec/e2e/capybara/spec/a11y_spec.rb
> feat: update to use `axe-core@4.2.2`

- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
> feat: update to use `axe-core@4.2.3`

- error-handling.md
- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
- packages/axe-core-api/lib/axe/api/run.rb
- packages/axe-core-api/lib/axe/configuration.rb
- packages/axe-core-api/lib/axe/core.rb
- packages/axe-core-api/lib/loader.rb
> feat: add legacy mode and 4.3.x tests

- .github/workflows/sync-master-develop.yml
> ci: update sync GH action

- error-handling.md
> docs: error handling

- packages/axe-core-api/lib/axe/api/run.rb
> chore: remove unused backtick

- packages/axe-core-api/lib/axe/api/run.rb
> chore: add error handling url to switchToWindow err

- CHANGELOG.md
- package.json
- packages/axe-core-api/lib/axe/api/run.rb
- version.rb
> chore: release v4.3.1

- packages/axe-core-api/lib/axe/api/run.rb
> fix: finishRun stack overflow

- CHANGELOG.md
- package.json
- packages/axe-core-api/lib/axe/api/run.rb
- version.rb
> chore: release v4.3.2

- packages/axe-core-rspec/README.md
New PR for https://github.com/dequelabs/axe-core-gems/pull/218 in order to make CircleCI happy.
> docs: use strings for rules with dashes

- .circleci/config.yml
- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
> feat: update axe-core to v4.3.5

- .circleci/config.yml
- CHANGELOG.md
- package.json
- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
- packages/axe-core-rspec/README.md
- version.rb
> chore: release v4.4.0

- .circleci/config.yml
> ci: update docker image

- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
upgrade axe-core to 4.4.2 (in order to fix contrast error issue)
Closes issue: #236
> feat: upgrade axe-core to 4.4.2

- .circleci/config.yml
- CHANGELOG.md
- package.json
- packages/axe-core-api/lib/axe/api/value_object.rb
- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
- version.rb
> chore: release v4.4.1

- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
Ref: https://github.com/dequelabs/axe-core-gems/issues/251
> chore: update to use axe-core 4.4.3

- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
> fix: update to use axe-core 4.5.1

- .circleci/config.yml
> ci: update to use `cimg/go:1.17.1`

- package.json
- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
> fix: update to use axe-core 4.5.2

- .github/workflows/create-release.yml
> ci: use npm install instead of ci

- .github/PULL_REQUEST_TEMPLATE.md
<< We never use this anyway >>
> chore: Remove PR template

- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
- packages/axe-core-api/lib/axe/api/context.rb
- packages/axe-core-api/lib/axe/api/selector.rb
https://github.com/dequelabs/axe-core-gems/issues/284
> test: add tests for 4.6 selectors

- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
- packages/axe-core-api/lib/axe/api/results.rb
Closes: https://github.com/dequelabs/axe-devtools-gems/issues/347
> fix(api): properly set timestamp

- packages/axe-core-watir/lib/axe-watir.rb
https://github.com/dequelabs/axe-core-gems/issues/304
Do not ask me why this works
> fix(watir): spawn firefox windows on windows

- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
Closes: https://github.com/dequelabs/axe-core-gems/issues/333
> fix(axe-core-api): pin axe-core version to accept patch updates only

- .github/workflows/update-axe-core.yml
https://github.com/dequelabs/axe-api-team/issues/391
No QA required
> ci: auto update axe-core

- .github/workflows/create-release-candidate.yml
Closes: https://github.com/dequelabs/axe-core-gems/issues/342
> ci: add `create-release-candidate.yml` workflow

- .circleci/config.yml
Closes: https://github.com/dequelabs/axe-core-gems/issues/345
> ci: add release branch check to circleci config.yml

- package-lock.json
- package.json
Fixes the broken lazy load iframe tests.
Ref: https://github.com/dequelabs/axe-core-npm/pull/1052
No QA needed.
> chore: update test-fixtures to fix lazy load

- .circleci/config.yml
> ci: remove chromedriver pin

- .circleci/config.yml
- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
> ci: update circleCI container size

- .circleci/config.yml
- CHANGELOG.md
- package.json
- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
- version.rb
> Release 4.10.2

- .github/workflows/sync-master-develop.yml
> ci: update action-sync action to v1

- .circleci/config.yml
> chore: update orbs

- .circleci/config.yml
- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
> fix: Update axe-core to v4.10.3

- .circleci/config.yml
- .github/CODEOWNERS
- .github/workflows/sync-master-develop.yml
- CHANGELOG.md
- package.json
- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
- version.rb
> chore: Release 4.10.3

- .circleci/config.yml
- packages/axe-core-selenium/README.md
- packages/axe-core-selenium/lib/axe-selenium.rb
- packages/axe-core-selenium/spec/axe-selenium_spec.rb
> fix: allow passing extra options to Selenium::WebDriver
