- lib/axe/api/results.rb
- lib/axe/api/results/check.rb
- lib/axe/api/results/checked_node.rb
- lib/axe/api/results/node.rb
- lib/axe/api/results/rule.rb
Provide a nicer format for displaying violation messages.
@jasonkarns Can you give it a look over?
> Give violation messages some indentation hierarchy for readability

- lib/axe/api/results/checked_node.rb
- lib/axe/api/results/node.rb
- lib/axe/api/results/rule.rb
- spec/lib/axe/api/results_spec.rb
This closes dequelabs/axe-matchers#9
Creating a test as an example of malformed results, and adding the
appropriate nil checks for formatting the message displayed in the test
results.
> More graceful handling of malformed results returned from axe-core

- axe-matchers.gemspec
- Updates axe-matchers gem version to 1.3.0
- Upates axe-core npm version to 2.0.5
> Bumps version number for axe-core 2.0 release

- lib/axe/loader.rb
- lib/webdriver_script_adapter/frame_adapter.rb
- lib/webdriver_script_adapter/query_selector_adapter.rb
- spec/lib/axe/loader_spec.rb
Capybara has deprecated the `:tag_name` selector for `find_elements`. This PR was originally started by @ohrite as #17. Please see that PR for discussion around the deprecation and the approach to the fix.
> Minifast capybara tag name deprecation

- axe-matchers.gemspec
- docs/Cucumber.md
- lib/axe/api/a11y_check.rb
- lib/axe/api/context.rb
- lib/axe/api/options.rb
- lib/axe/core.rb
- lib/webdriver_script_adapter/execute_async_script_adapter.rb
- spec/lib/axe/api/a11y_check_spec.rb
- spec/lib/axe/api/context_spec.rb
- spec/lib/axe/api/options_spec.rb
- spec/lib/webdriver_script_adapter/execute_async_script_adapter_spec.rb
* Upgrades axe-core to version 2.3.1
* Upgrades gem dependencies
* Replaces axe.a11yCheck with axe.run
`axe.a11yCheck` has been deprecated, so this commit replaces it with
`axe.run`
The old signature for `axe.a11yCheck` was:
``` rb
// with populated context and options axe.a11yCheck(context, options,
function(results) { ... });
// with empty context and options axe.a11yCheck({}, {}, function(results) {
... });
```
The new signature for `axe.run` is:
``` rb
// with populated context and options axe.run(context, options,
function(err, results) { ... });
// with empty context and options axe.run(function(err, results) { ... });
```
> Updates axe-core, and replaces axe.a11yCheck with axe.run

- .gitignore
- Brewfile
- CONTRIBUTING.md
- README.md
- Rakefile
- axe-matchers.gemspec
- circle.yml
- config/cucumber.yml
- examples/capybara/features/support/env.rb
- examples/selenium/features/support/env.rb
- examples/watir/features/support/env.rb
- features/iframes.feature
- features/support/env/capybara.rb
- package.json
- spec/integration_spec.rb
- spec/lib/axe/api/results_spec.rb
- spec/lib/webdriver_script_adapter/exec_eval_script_adapter_spec.rb
This PR removes the deprecated PhantomJS and Poltergeist drivers and updates to Capybara's selenium_chrome_headless driver instead. It also updates to axe-core@3x, which required changing some of the fixtures tested and adding an extra test for Shadow DOM selectors. But it appears that axe-matchers was written to already handle selector arrays like the `target` returned from axe-core@3x.
From [API.md](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md): 
> `target`: Array of either strings or Arrays of strings. If the item in the array is a string, then it is a CSS selector. If there are multiple items in the array each item corresponds to one level of iframe or frame. If there is one iframe or frame, there should be two entries in target. If there are three iframe levels, …
> Axe 3 upgrade

- lib/axe/api/run.rb
- lib/axe/matchers/be_accessible.rb
- spec/lib/axe/api/run_spec.rb
- spec/lib/axe/core_spec.rb
- spec/lib/axe/matchers/be_accessible_spec.rb
Swapping out `a11y_check` for `run` seemed like a good thing to do ahead of a major release. The API method is used in the matchers but isn't called directly, so it seems like a low-risk change.
> Deprecate a11ycheck

- axe-matchers.gemspec
- lib/axe/api/results.rb
- lib/axe/api/results/check.rb
- lib/axe/api/results/checked_node.rb
- lib/axe/api/results/rule.rb
- package.json
The following changes have been made:
> fix: extend generated results to match axe-core results 

- axe-matchers.gemspec
- lib/axe/api/results.rb
- lib/axe/api/results/check.rb
- lib/axe/api/results/checked_node.rb
- lib/axe/api/results/rule.rb
- package.json
fix: extend generated results to match axe-core results  (#37)
> feat: release 2.1.1

- .circleci/config.yml
- .circleci/publish.sh
This patch adds CircleCI configuration for automatically publishing "pre" and "production" gems to Ruby Gems when commits land into develop and master.
> ci: setup automated releases for "develop" and "master" commits

- .circleci/publish.sh
It appears the `sed` on CircleCI is slightly different than what I have on OSX. This patch updates the `sed` command to work on CI.
NOTE: I have SSH'ed into CircleCI to validate this works.
Closes issue:
> build(publish.sh): fix sed command

- .circleci/publish.sh
This patch adds a missing `ls` to our `.circleci/publish.sh` script. I have no idea why I removed it in #46, as nothing works without it.
`/giphy facepalm`
> ci: fix `gem push` command

- .circleci/config.yml
This patch ensures the latest (stable) version of `npm` is used on CI.
> ci: ensure latest npm is used

- .circleci/config.yml
This patch refactors our CircleCI configuration significantly. Now, rather than using a single job, we run the tests and release separately. Additionally, a `github_release` job has been created which pushes a GitHub Release (tag) to GitHub after a successful production deployment.
NOTE: we're still not caching dependencies here, but this should not "slow" us down too much, since the additional time spent fetching deps will only happen during a release.
> ci: create GitHub release for production versions [WWD-1845]

- .circleci/config.yml
Caching `bundler` dependencies
Reference: https://circleci.com/docs/2.0/caching/#bundler-ruby, which shows the need to run `bundle clean`.
Closes issue:
- https://github.com/dequelabs/axe-matchers/issues/47
> chore: update circle config to cache dependencies

- .circleci/config.yml
- examples/capybara/features/a11y.feature
- examples/rspec-capybara/spec/a11y_spec.rb
- examples/selenium/features/a11y.feature
- examples/watir/features/a11y.feature
- lib/axe/cucumber/step.rb
- package.json
- spec/lib/axe/cucumber/step_regex_spec.rb
As of `> cucumber 2.2` named capture groups in regular expressions has been deprecated, which lead to an error like below, when using `axe-matchers` with latest version of cucumber.
See also, [this thread](https://github.com/cucumber/cucumber/issues/329#issuecomment-361783591) which highlights why named capture groups were disallowed in cucumber, for further context.
**This PR does the below:**
- updates the regex to not use named capture groups but still have the benefit of capture groups, thus allowing for axe matchers to play well with latest version of cucumber.
- update specs to adapt to capture groups over named capture groups
- updates the example test cases to actually test against nodes in the provided url.
- runs examples tests in CI (closed separate PR …
> fix: not use named capture groups in cucumber step regex

- .circleci/config.yml
This is to make sure, that we do not `next` release a half baked solution.
Partially tackles:
- https://github.com/dequelabs/axe-core-gems/issues/98
> ci: ignore `test` and `next` builds during rebranding work

- packages/axe-core-capybara/README.md
- packages/axe-core-capybara/Rakefile
- packages/axe-core-capybara/lib/axe-capybara.rb
- packages/axe-core-capybara/spec/axe-capybara_spec.rb
- packages/axe-core-selenium/README.md
- packages/axe-core-selenium/Rakefile
- packages/axe-core-selenium/lib/axe-selenium.rb
- packages/axe-core-selenium/spec/axe-selenium_spec.rb
- packages/axe-core-watir/README.md
- packages/axe-core-watir/Rakefile
- packages/axe-core-watir/lib/axe-watir.rb
- packages/axe-core-watir/spec/axe-watir_spec.rb
Removes redundant switch block for each of the webdrivers - `AxeSelenium`, `AxeWatir` and `AxeCapybara`.
Closes issue: 
- NA
> refactor: allow to configure browser as a Symbol argument for webdrivers

- .circleci/config.yml
See: https://github.com/dequelabs/axe-core-gems/issues/167
This should fix github release script
https://github.com/google/link022/issues/89
> ci: update golang image

- packages/axe-core-cucumber/e2e/capybara/features/step_definitions/steps.rb
- packages/axe-core-cucumber/e2e/capybara/features/support/env.rb
So apparently our cucumber capybara tests never worked? What was happening was that a page would open, it would go to "http://abcdcomputech.dequecloud.com/", then it would close and a new page would be opened so that we could run axe on `about:blank`. This makes sure we actually run axe on the page we navigate to.
Closes issue: https://github.com/dequelabs/axe-core-gems/issues/183
> test: properly scan page in cucumber e2e test

- packages/axe-core-api/lib/axe/configuration.rb
- packages/axe-core-api/lib/axe/core.rb
- packages/axe-core-api/lib/webdriver_script_adapter/frame_adapter.rb
semi-breaking change: Runs in iframes by defalut.
Before, `skip_iframes` had been set to true by default.
Closes issue: https://github.com/dequelabs/axe-core-gems/issues/164
> fix: correctly run on iframes

- packages/axe-core-api/lib/axe/core.rb
- packages/axe-core-api/spec/axe/core_spec.rb
This is needed to support 4.3.x in devtools
> chore: add `call_verbatim` method

- packages/axe-core-api/axe-core-api.gemspec
cherry-picking commits from https://github.com/dequelabs/axe-core-gems/pull/203 to get CircleCI to run properly
> fix: make webdriver frameworks to development dependencies

- packages/axe-core-api/lib/axe/api/value_object.rb
I was trying to setup Axe in my Minitest test suite (following the general idea presented [here](170)), and I hit an error that took me a while to track down. I was using this as my helper method:
```ruby
def assert_accessible(page)
matcher = Axe::Matchers::BeAxeClean.new
assert(matcher.matches?(page), matcher.failure_message)
end
```
and in my `assert` call I kept getting this error:
```
NoMethodError: undefined method `reject' for nil:NilClass
```
After digging into the backtrace and your source code, I found that the source of the problem was building up the `failure_message` for the audit results:
https://github.com/dequelabs/axe-core-gems/blob/5a82425b2bbf494e191f8d0ab17537e8e58a832d/packages/axe-core-api/lib/axe/api/results.rb#L44
In my case, I was hitting a problem when inspecting …
> fix: Allow `none` values for ValueObject, since can be set by CheckedNode result type

- packages/axe-core-api/lib/axe/api/value_object.rb
Repushed https://github.com/dequelabs/axe-core-gems/pull/228 so that CI can run
> chore: Allow `none` values for ValueObject

- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
- packages/axe-core-api/lib/axe/api/run.rb
https://github.com/dequelabs/axe-devtools-npm/issues/1653
Note: 60mil broke webdriver locally. Reduced to 20mil and it works. idk why but I blame ruby
> fix: work with extremely large results

- CHANGELOG.md
- package.json
- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
- packages/axe-core-capybara/lib/axe-capybara.rb
- packages/axe-core-capybara/spec/axe-capybara_spec.rb
- packages/axe-core-rspec/e2e/capybara/spec/a11y_spec.rb
- packages/axe-core-rspec/e2e/capybara/spec/spec_helper.rb
- packages/axe-core-watir/lib/axe-watir.rb
- version.rb
* Update axe-core to v4.7.0 ([#299](https://github.com/dequelabs/axe-core-gems/issues/299)) ([81ca285](https://github.com/dequelabs/axe-core-gems/commit/81ca285e2a8ebda7414b5d0543b732141ea6512d))
* **capybara:** open browser based on passed symbol ([#303](https://github.com/dequelabs/axe-core-gems/issues/303)) ([c43ee49](https://github.com/dequelabs/axe-core-gems/commit/c43ee49744133ca22a32dde767d896b376c77b6c))
* **capybara:** open selected browser ([#305](https://github.com/dequelabs/axe-core-gems/issues/305)) ([311e4da](https://github.com/dequelabs/axe-core-gems/commit/311e4dabfe711c6d2bb0e37e113a86d4c4edcf6a))
* **capybara:** respect browser choice ([#307](https://github.com/dequelabs/axe-core-gems/issues/307)) ([bb0471d](https://github.com/dequelabs/axe-core-gems/commit/bb0471d6ce31c4 …
> chore(release): 4.7.0

- .github/scripts/prepare_release.sh
- .github/workflows/auto-patch-release.yml
- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
- packages/axe-core-api/lib/axe/api/run.rb
https://github.com/dequelabs/axe-api-team/issues/333
> ci: auto patch-release every 2 weeks

- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
- packages/axe-core-api/lib/axe/api/run.rb
- packages/axe-core-api/lib/axe/core.rb
- packages/axe-core-api/spec/axe/core_spec.rb
https://github.com/dequelabs/axe-core-gems/issues/313
> fix: gracefully handle unloaded iframes

- packages/axe-core-api/lib/axe/api/run.rb
- packages/axe-core-api/spec/axe/api/run_spec.rb
Closes issue: https://github.com/dequelabs/axe-core-gems/issues/320
I have not been able to replicate the issue. Nor can I find in our code where we might return `nil`. So I decided to handle it like a frame erroring: We mark the frame with `frame-tested` if its an inner frame and just throw if it is top-level.
> fix: handle spurious axe.runPartial returning null

- .github/scripts/prepare_release.sh
- .github/workflows/auto-patch-release.yml
Test PR: https://github.com/dequelabs/axe-core-gems/pull/323
Test issue: https://github.com/dequelabs/axe-core-gems/issues/322
Conditional checks were tested in a personal repo: https://github.com/AdnoC/action-test/actions/workflows/push-and-dispatch.yml
https://github.com/dequelabs/axe-api-team/issues/355
https://github.com/dequelabs/axe-api-team/issues/342
> ci: enable manual run of patch release

- .github/scripts/prepare_release.sh
- package.json
This PR allows the unnamed argument to be optional, if it's not specified it will default to commit-and-tag-version handling version, otherwise it will release as the specified release level.
<details>
<summary>Without specifying a release level</summary>
</details>
<details>
<summary>With release level</summary>
</details>
Closes: https://github.com/dequelabs/axe-core-gems/issues/337
> ci: update `prepare_release.sh` to take optional release level

- .github/scripts/prepare_release.sh
The release script is failing due to the new changelogs not being generated
no qa required
> ci: generate changelogs with `commit-and-tag-version`

- .circleci/config.yml
- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
- packages/axe-core-api/lib/axe/api.rb
- packages/axe-core-api/lib/axe/matchers/be_axe_clean.rb
It saves 95% of load time when doing `require "axe-rspec"`.
The time is actually spent loading the `virtus` library. Deferring the loading of `Axe::API::Run` until needed does in turn defer the loading of `virtus` library.
No QA required.
> fix: add `Lazy-load Axe::API::Run` to improve boot time

- .circleci/config.yml
- .github/workflows/sync-master-develop.yml
- CHANGELOG.md
- package-lock.json
- package.json
- packages/axe-core-api/e2e/selenium/spec/api_spec.rb
- packages/axe-core-api/lib/axe/api.rb
- packages/axe-core-api/lib/axe/matchers/be_axe_clean.rb
- packages/axe-core-api/package-lock.json
- packages/axe-core-api/package.json
- version.rb
> Release v4.10.0

- .circleci/config.yml
When running CI on [another PR](https://github.com/dequelabs/axe-core-gems/pull/404), Selenium would consistently fail with 
```
Failure/Error: $driver.get fixture "/index.html"
Selenium::WebDriver::Error::InvalidSessionIdError: invalid session id
```
This [appears to be due to resourcing issues for new versions of Chrome](https://stackoverflow.com/questions/56002701/selenium-webdriver-error-invalid-session-id); pinning the Chrome version in CI consistently fixes the issue.
No QA needed.
> ci: pin Chrome

- packages/axe-core-api/axe-core-api.gemspec
- packages/axe-core-cucumber/axe-core-cucumber.gemspec
- packages/axe-core-rspec/axe-core-rspec.gemspec
Closes #402 
Background: ostruct (aka OpenStruct) is part of Ruby's standard library, but it's being pulled out of the standard library and into a gem. For now, both versions are available. If you require the version from the standard library, Ruby 3.3.5 will print a warning urging you to switch over to using the gem version. In Ruby 3.5.0, the standard library version will not exist.
The warning looks like this:
```
/Users/mjacobson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/virtus-2.0.0/lib/virtus.rb:1: warning: /Users/mjacobson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the …
```
> chore: Install ostruct alongside virtus

- .github/workflows/sync-master-develop.yml
> ci: remove `PR_TEMPLATE` from sync workflow

- .circleci/config.yml
- CHANGELOG.md
- package.json
- version.rb
Fixes merge conflicts for 
https://github.com/dequelabs/axe-core-gems/pull/447
No QA required
> chore: fix merge conflicts into develop
